// <auto-generated />
using System;
using CalorieCalculate.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalorieCalculate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220221174707_ikinci_migration")]
    partial class ikinci_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Calorie")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("MealDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TypeMealId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeMealId");

                    b.ToTable("Yemek Bilgileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorie = 114000.0,
                            MealDescription = "1 porsiyon, 1 su bardağı, 200 ml",
                            MealName = "Süt",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 2,
                            Calorie = 114000.0,
                            MealDescription = "1 porsiyon, 1 kase, 200 gram",
                            MealName = "Yoğurt",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 3,
                            Calorie = 114000.0,
                            MealDescription = "1 porsiyon, 2 yemek kaşığı, 50 gram",
                            MealName = "Süzme Yoğurt",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 4,
                            Calorie = 57000.0,
                            MealDescription = "1 porsiyon, 1 su bardağı, 200 ml",
                            MealName = "Ayran",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 5,
                            Calorie = 114000.0,
                            MealDescription = "1 porsiyon, 1 su bardağı, 200 ml",
                            MealName = "Kefir",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 6,
                            Calorie = 57000.0,
                            MealDescription = "1 porsiyon, 1 kutu, 125 gram",
                            MealName = "Probiyotik Yoğurt",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 7,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Beyaz Peynir",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 8,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Labne Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 9,
                            Calorie = 120000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Kaşar Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 10,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Dil Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 11,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 3 yemek kaşığı, 70 gram",
                            MealName = "Yağsız Lor Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 12,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 yemek kaşığı, 70 gram",
                            MealName = "Tulum Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 13,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 2 adet, 50 gram",
                            MealName = "Üçgen Karper Peynir",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 14,
                            Calorie = 97000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Otlu Peynir",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 15,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Hellim Peyniri",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 16,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 kibrit kutusu, 30 gram",
                            MealName = "Mozarella",
                            TypeMealId = 1
                        },
                        new
                        {
                            Id = 17,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 köfte kadar, 30 gram",
                            MealName = "Kıyma",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 18,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 avuç büyüklükte, 30 gram",
                            MealName = "Köfte",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 19,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 4 adet, 30 gram",
                            MealName = "Kuşbaşı",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 20,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy, 30 gram",
                            MealName = "Bonfile",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 21,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 köfte kadar, 30 gram",
                            MealName = "Tavuk-Hindi",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 22,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 adet, 50 gram",
                            MealName = "Yumurta",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 23,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 köfte kadar, 30 gram",
                            MealName = "Balık",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 24,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 1 yemek kaşığı, 30 gram",
                            MealName = "Ton Balığı",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 25,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 5 ince halka, 30 gram",
                            MealName = "Sucuk",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 26,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 2 ince dilim, 30 gram",
                            MealName = "Pastırma",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 27,
                            Calorie = 69000.0,
                            MealDescription = "1 porsiyon, 3 dilim, 40 gram",
                            MealName = "Hindi/Piliç Jambon",
                            TypeMealId = 2
                        },
                        new
                        {
                            Id = 28,
                            Calorie = 80000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı, 25 gram",
                            MealName = "Nohut",
                            TypeMealId = 3
                        },
                        new
                        {
                            Id = 29,
                            Calorie = 80000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı, 25 gram",
                            MealName = "Kurufasulye",
                            TypeMealId = 3
                        },
                        new
                        {
                            Id = 30,
                            Calorie = 80000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı, 25 gram",
                            MealName = "Mercimek",
                            TypeMealId = 3
                        },
                        new
                        {
                            Id = 31,
                            Calorie = 80000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı, 25 gram",
                            MealName = "Barbunya",
                            TypeMealId = 3
                        },
                        new
                        {
                            Id = 32,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 ince dilim, 25 gram",
                            MealName = "Ekmek(kepek,buğday,çavdar,mısır)",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 33,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 küçük kase, 160 gram",
                            MealName = "Çorba",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 34,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 3 yemek kaşığı, 50 gram",
                            MealName = "Pirinç/Bulgur pilavı",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 35,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 3 yemek kaşığı, 50 gram",
                            MealName = "Makarna/Erişte",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 36,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy, 90 gram",
                            MealName = "Haşlanmış Patates",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 37,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 2 yemek kaşığı, 40 gram",
                            MealName = "Haşlanmış Tane Mısır",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 38,
                            Calorie = 103000.0,
                            MealDescription = "1 porsiyon, 1 Kase , 30 gram",
                            MealName = "Kahvaltılık Gevrek",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 39,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 Su Bardağı , 20 gram",
                            MealName = "Patlamış Mısır(yağsız)",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 40,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1.5 Adet , 20 gram",
                            MealName = "Galeta sade(Büyük)",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 41,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 7 Adet , 20 gram",
                            MealName = "Galeta sade(Küçük)",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 42,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1/3 Adet , 25 gram",
                            MealName = "Simit(susamlı)",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 43,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 2-3 orta boy , 45 gram",
                            MealName = "Kestane",
                            TypeMealId = 4
                        },
                        new
                        {
                            Id = 44,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Bamya(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 45,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Brokoli(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 46,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Ebegümeci(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 47,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Ispanak(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 48,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Karnabahar(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 49,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Lahana(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 50,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Mantar",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 51,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Patlıcan(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 52,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Pazı(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 53,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Semizotu(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 54,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Taze Fasulye(Pişmiş)",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 55,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Bakla",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 56,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Bezelye",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 57,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 1 orta boy , 200 gram",
                            MealName = "Enginar",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 58,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Havuç",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 59,
                            Calorie = 25000.0,
                            MealDescription = "1 porsiyon, 4 yemek kaşığı , 200 gram",
                            MealName = "Kereviz",
                            TypeMealId = 5
                        },
                        new
                        {
                            Id = 60,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy , 120 gram",
                            MealName = "Elma",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 61,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy , 120 gram",
                            MealName = "Armut",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 62,
                            Calorie = 103000.0,
                            MealDescription = "1 porsiyon, 1 orta boy , 220 gram",
                            MealName = "Portakal",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 63,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 büyük boy , 150 gram",
                            MealName = "Mandalina",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 64,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy , 150 gram",
                            MealName = "Greyfurt",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 65,
                            Calorie = 150000.0,
                            MealDescription = "1 porsiyon, 1 orta boy , 60 gram",
                            MealName = "Muz",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 66,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 orta boy , 120 gram",
                            MealName = "Kivi",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 67,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 3 halka , 120 gram",
                            MealName = "Ananas",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 68,
                            Calorie = 98000.0,
                            MealDescription = "1 porsiyon, 1 orta boy , 250 gram",
                            MealName = "Ayva",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 69,
                            Calorie = 120000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy , 200 gram",
                            MealName = "Nar",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 70,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 15 iri adet , 100 gram",
                            MealName = "üzüm",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 71,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 6 adet , 100 gram",
                            MealName = "Yeni Dünya",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 72,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 4 adet , 120 gram",
                            MealName = "Kayısı",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 73,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 5 adet , 85 gram",
                            MealName = "Erik",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 74,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 adet , 100 gram",
                            MealName = "İncir",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 75,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 8 iri adet , 90 gram",
                            MealName = "Kiraz",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 76,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 4 adet , 20 gram",
                            MealName = "Kuru Kayısı",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 77,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 küçük boy , 20 gram",
                            MealName = "Kuru İncir",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 78,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 5 Adet, 20 gram",
                            MealName = "Kuru Erik",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 79,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 yemek kaşığı, 20 gram",
                            MealName = "Kuru Üzüm",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 80,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 3 adet, 20 gram",
                            MealName = "Hurma",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 81,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 15 adet küçük , 150 gram",
                            MealName = "Çilek",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 82,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 orta boy, 120 gram",
                            MealName = "Şeftali",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 83,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 ince dilim, 200 gram",
                            MealName = "Kavun",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 84,
                            Calorie = 60000.0,
                            MealDescription = "1 porsiyon, 1 ince dilim, 200 gram",
                            MealName = "Karpuz",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 85,
                            Calorie = 99000.0,
                            MealDescription = "1 porsiyon, 1 bardak, 200 ml",
                            MealName = "Vişne Suyu",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 86,
                            Calorie = 98000.0,
                            MealDescription = "1 porsiyon, 1 bardak, 200 ml",
                            MealName = "Elma Suyu",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 87,
                            Calorie = 120000.0,
                            MealDescription = "1 porsiyon, 1 bardak, 200 ml",
                            MealName = "Portakal Suyu",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 88,
                            Calorie = 106000.0,
                            MealDescription = "1 porsiyon, 1 bardak, 200 ml",
                            MealName = "Nar Suyu",
                            TypeMealId = 6
                        },
                        new
                        {
                            Id = 89,
                            Calorie = 45000.0,
                            MealDescription = "1 porsiyon, 5 adet, 15 gram",
                            MealName = "Zeytin",
                            TypeMealId = 7
                        },
                        new
                        {
                            Id = 90,
                            Calorie = 45000.0,
                            MealDescription = "1 porsiyon, 1 tatlı kaşığı , 5 gram",
                            MealName = "Zeytinyağı",
                            TypeMealId = 7
                        },
                        new
                        {
                            Id = 91,
                            Calorie = 45000.0,
                            MealDescription = "1 porsiyon, 1 tatlı kaşığı, 5 gram",
                            MealName = "Bitkisel sıvıyağ",
                            TypeMealId = 7
                        },
                        new
                        {
                            Id = 92,
                            Calorie = 45000.0,
                            MealDescription = "1 porsiyon, 1 tatlı kaşığı, 5 gram",
                            MealName = "Tereyağ",
                            TypeMealId = 7
                        },
                        new
                        {
                            Id = 93,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 yemek kaşığı, 30 gram",
                            MealName = "Bal",
                            TypeMealId = 8
                        },
                        new
                        {
                            Id = 94,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 3 tatlı kaşığı, 30 gram",
                            MealName = "Reçel",
                            TypeMealId = 8
                        },
                        new
                        {
                            Id = 95,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 3 tatlı kaşığı, 30 gram",
                            MealName = "Marmelat",
                            TypeMealId = 8
                        },
                        new
                        {
                            Id = 96,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 3 tatlı kaşığı, 30 gram",
                            MealName = "Pekmez",
                            TypeMealId = 8
                        },
                        new
                        {
                            Id = 97,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 çay bardağı, 20 gram",
                            MealName = "Leblebi",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 98,
                            Calorie = 45000.0,
                            MealDescription = "1 porsiyon, 2 adet, 8 gram",
                            MealName = "Ceviz içi",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 99,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 avuç, 10 gram",
                            MealName = "Ay Çekirdeği",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 100,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 1 avuç, 10 gram",
                            MealName = "Kabak Çekirdeği",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 101,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 5 adet, 10 gram",
                            MealName = "Badem içi",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 102,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 7 adet, 10 gram",
                            MealName = "Fındık içi",
                            TypeMealId = 9
                        },
                        new
                        {
                            Id = 103,
                            Calorie = 68000.0,
                            MealDescription = "1 porsiyon, 7 adet, 10 gram",
                            MealName = "Fıstık içi",
                            TypeMealId = 9
                        });
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Repast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("RepastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Öğün Bilgileri");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.RepastMeal", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("RepastId")
                        .HasColumnType("int");

                    b.Property<double>("EatenPortion")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("MealImage")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("MealId", "RepastId");

                    b.HasIndex("RepastId");

                    b.ToTable("ÖğünYemek");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.TypeOfMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Yemek Grupları");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealType = "Süt Grubu"
                        },
                        new
                        {
                            Id = 2,
                            MealType = "Et Grubu"
                        },
                        new
                        {
                            Id = 3,
                            MealType = "Kurubaklagil Grubu"
                        },
                        new
                        {
                            Id = 4,
                            MealType = "Ekmek Grubu"
                        },
                        new
                        {
                            Id = 5,
                            MealType = "Sebze Grubu"
                        },
                        new
                        {
                            Id = 6,
                            MealType = "Meyve Grubu"
                        },
                        new
                        {
                            Id = 7,
                            MealType = "Yağ Grubu"
                        },
                        new
                        {
                            Id = 8,
                            MealType = "Tatlı Grubu"
                        },
                        new
                        {
                            Id = 9,
                            MealType = "Kuruyemiş Grubu"
                        });
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Kullanıcı");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.UserInformation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Kullanıcı Bilgileri");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Meal", b =>
                {
                    b.HasOne("CalorieCalculate.Model.Entities.TypeOfMeal", "TypeOfMeal")
                        .WithMany("Meals")
                        .HasForeignKey("TypeMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeOfMeal");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Repast", b =>
                {
                    b.HasOne("CalorieCalculate.Model.Entities.User", "User")
                        .WithMany("Repasts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.RepastMeal", b =>
                {
                    b.HasOne("CalorieCalculate.Model.Entities.Meal", "Meal")
                        .WithMany("RepastMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieCalculate.Model.Entities.Repast", "Repast")
                        .WithMany("RepastMeals")
                        .HasForeignKey("RepastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Repast");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.UserInformation", b =>
                {
                    b.HasOne("CalorieCalculate.Model.Entities.User", "User")
                        .WithOne("UserInformation")
                        .HasForeignKey("CalorieCalculate.Model.Entities.UserInformation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Meal", b =>
                {
                    b.Navigation("RepastMeals");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.Repast", b =>
                {
                    b.Navigation("RepastMeals");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.TypeOfMeal", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("CalorieCalculate.Model.Entities.User", b =>
                {
                    b.Navigation("Repasts");

                    b.Navigation("UserInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
